opencloud:
  common:
    user-info-uri: ${opencloud.common.api-server-addr}/admin/current/user
    client-secret: 0osTIhce7uPvDKHz6aa67bhCukaKoYl4
    auth-server-addr: http://localhost:8211
    scope: userProfile
    jwt-signing-key: 2cde1eaa60fe4af1987f94caa13f29a2
    token-info-uri: ${opencloud.common.api-server-addr}/admin/oauth/check_token
    access-token-uri: ${opencloud.common.api-server-addr}/admin/oauth/token
    api-server-addr: http://localhost:8888
    client-id: 7gBZcbsC7kLIWCdELIl8nxcs
    user-authorization-uri: ${opencloud.common.auth-server-addr}/oauth/authorize
    admin-server-addr: http://localhost:8080
  swagger2:
    client-secret: ${opencloud.common.client-secret}
    scope: ${opencloud.common.scope}
    access-token-uri: ${opencloud.common.access-token-uri}
    client-id: ${opencloud.common.client-id}
    user-authorization-uri: ${opencloud.common.user-authorization-uri}
    enabled: true
